<a href="https://colab.research.google.com/github/Chethan2627/Chethan2627/blob/main/Copy_of_Finding_largest_Eigen_value_and_eigen_vector_by_rallinges_power.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Finding largest Eigen value and eigen vector For A [ 1 9 8, 2 7 6, 7 20 9]
taking initial eigen vector X =[4 2 -8]

In [ ]:
import numpy as np
from numpy.linalg import eig
A=np.array([[1,9,8],[2,7,6],[7,20,9]])
X=np.array([4,2,-8])
print("\n Given Matrix:\n",A)
print("\n Given initial eigen vector:\n",X)
max_iterations=10
for i in range(max_iterations):
  X=np.dot(A,X)
  eigenValue = np.linalg.norm(X)
  X =X/eigenValue
  print(eigenValue,X)
print('largent eigen value:',eigenValue)
print('corresponding eigen vectot:',X)


 Given Matrix:
 [[ 1  9  8]
 [ 2  7  6]
 [ 7 20  9]]

 Given initial eigen vector:
 [ 4  2 -8]
49.558046773455466 [-0.84749103 -0.5246373  -0.08071343]
19.158434242021535 [-0.32439677 -0.30543852 -0.89525083]
21.011661702390843 [-0.48712711 -0.3882781  -0.7822706 ]
22.516527253707686 [-0.45476795 -0.37242975 -0.80900074]
22.284328788073974 [-0.46124977 -0.37562489 -0.80383741]
22.333684243756068 [-0.45995873 -0.37498955 -0.80487316]
22.323968911925764 [-0.4602161  -0.37511624 -0.80466698]
22.325910091721582 [-0.46016481 -0.37509099 -0.80470808]
22.325523375976115 [-0.46017503 -0.37509602 -0.80469989]
22.32560046229768 [-0.46017299 -0.37509502 -0.80470152]
largent eigen value: 22.32560046229768
corresponding eigen vectot: [-0.46017299 -0.37509502 -0.80470152]


Finding largest Eigen value and eigen vector For A [ 25 1 2 , 1 3 0, 2 0 -4]
taking initial eigen vector X =[1 0 0]

In [ ]:

import numpy as np
from numpy.linalg import eig
A=np.array([[25,1,2],[1,3,0],[2,0,-4]])
X=np.array([1,0,0])
print("\n Given Matrix:\n",A)
print("\n Given initial eigen vector:\n",X)
max_iterations=5
for i in range(max_iterations):
  X=np.dot(A,X)
  eigenValue = np.linalg.norm(X)
  X =X/eigenValue
  print(eigenValue,X)
print('largent eigen value:',eigenValue)
print('corresponding eigen vectot:',X)


 Given Matrix:
 [[25  1  2]
 [ 1  3  0]
 [ 2  0 -4]]

 Given initial eigen vector:
 [1 0 0]
25.099800796022265 [0.99602384 0.03984095 0.07968191]
25.18023916575147 [0.9968055  0.04430247 0.0664537 ]
25.18210418038798 [0.99663424 0.04486174 0.06861207]
25.18215016294369 [0.99665603 0.04492148 0.0682555 ]
25.18215134417317 [0.99665167 0.04492946 0.06831386]
largent eigen value: 25.18215134417317
corresponding eigen vectot: [0.99665167 0.04492946 0.06831386]


Finding largest Eigen value and eigen vector For A [ 2 -1 0, -1 2 -1, 0 -1 2] taking initial eigen vector X =[1 1 1]

In [ ]:
import numpy as np
from numpy.linalg import eig
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
X=np.array([1,1,1])
print("\n Given Matrix:\n",A)
print("\n Given initial eigen vector:\n",X)
max_iterations=6
for i in range(max_iterations):
  X=np.dot(A,X)
  eigenValue = np.linalg.norm(X)
  X =X/eigenValue
  print(eigenValue,X)
print('largent eigen value:',eigenValue)
print('corresponding eigen vectot:',X)


 Given Matrix:
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

 Given initial eigen vector:
 [1 1 1]
1.4142135623730951 [0.70710678 0.         0.70710678]
2.449489742783178 [ 0.57735027 -0.57735027  0.57735027]
3.3665016461206925 [ 0.51449576 -0.68599434  0.51449576]
3.412778753967126 [ 0.50251891 -0.70352647  0.50251891]
3.414171298655891 [ 0.50043309 -0.70649377  0.50043309]
3.4142123182220936 [ 0.50007433 -0.70700164  0.50007433]
largent eigen value: 3.4142123182220936
corresponding eigen vectot: [ 0.50007433 -0.70700164  0.50007433]
